version: '3.8'

services:
  db:
    restart: always
    container_name: db-myproject
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5438:${DB_PORT}

  app:
    build: .
    ports:
      - "5174:5174"
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db-data:
