// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth(arg1, arg2) {
  return window['go']['handler']['App']['Auth'](arg1, arg2);
}

export function AuthMiddleware(arg1) {
  return window['go']['handler']['App']['AuthMiddleware'](arg1);
}

export function CheckTodo(arg1) {
  return window['go']['handler']['App']['CheckTodo'](arg1);
}

export function CreateTodo(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['App']['CreateTodo'](arg1, arg2, arg3, arg4);
}

export function DeleteTodo(arg1) {
  return window['go']['handler']['App']['DeleteTodo'](arg1);
}

export function GenerateJWT(arg1, arg2) {
  return window['go']['handler']['App']['GenerateJWT'](arg1, arg2);
}

export function GetAllTodos() {
  return window['go']['handler']['App']['GetAllTodos']();
}

export function GetTodoByID(arg1) {
  return window['go']['handler']['App']['GetTodoByID'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['handler']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2) {
  return window['go']['handler']['App']['Register'](arg1, arg2);
}

export function RolePermissionMiddleware(arg1) {
  return window['go']['handler']['App']['RolePermissionMiddleware'](arg1);
}

export function UpdateTodo(arg1, arg2, arg3, arg4) {
  return window['go']['handler']['App']['UpdateTodo'](arg1, arg2, arg3, arg4);
}

export function ValidateJWT(arg1) {
  return window['go']['handler']['App']['ValidateJWT'](arg1);
}
