// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {time} from '../models';
import {domain} from '../models';
import {jwt} from '../models';

export function Auth(arg1:string,arg2:string):Promise<boolean>;

export function AuthMiddleware(arg1:string):Promise<context.Context>;

export function CheckTodo(arg1:string):Promise<void>;

export function CreateTodo(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<domain.Todo>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GenerateJWT(arg1:string,arg2:string):Promise<string>;

export function GetAllTodos():Promise<Array<domain.Todo>>;

export function GetTodoByID(arg1:string):Promise<domain.Todo>;

export function Login(arg1:string,arg2:string):Promise<{[key: string]: string}>;

export function Register(arg1:string,arg2:string):Promise<string>;

export function RolePermissionMiddleware(arg1:string):Promise<any>;

export function UpdateTodo(arg1:string,arg2:string,arg3:string,arg4:time.Time):Promise<domain.Todo>;

export function ValidateJWT(arg1:string):Promise<jwt.MapClaims>;
