// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {domain} from '../models';

export function CheckTodo(arg1:context.Context,arg2:string):Promise<void>;

export function CreateTodo(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:string):Promise<domain.Todo>;

export function DeleteTodo(arg1:context.Context,arg2:string):Promise<void>;

export function GetAllTodos(arg1:context.Context):Promise<Array<domain.Todo>>;

export function GetTodoByID(arg1:context.Context,arg2:string):Promise<domain.Todo>;

export function UpdateTodo(arg1:context.Context,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<domain.Todo>;
